server:
  address: 0.0.0.0
  servlet:
    context-path: /api

spring:
  application:
    name: stock-control-api

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    filter: true
  api-docs:
    path: /v3/api-docs
  show-actuator: false