services:
  db:
    image: postgres:18
    container_name: stock-control-db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - stock_control_pg:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak-db:
    image: postgres:18
    container_name: keycloak-db
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - keycloak_pg:/var/lib/postgresql/

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    container_name: stock-control-auth
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db

  api:
    build:
      context: ./stock-control-api
      dockerfile: Dockerfile
      target: dev

    container_name: stock-control-api
    working_dir: /work
    volumes:
      - ./stock-control-api:/work
      - maven-cache:/root/.m2
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_started
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/api/v3/api-docs || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s

  web:
    build:
      context: ./stock-control-web
      dockerfile: Dockerfile
    container_name: stock-control-web
    volumes:
      - ./stock-control-web:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "4200:4200"

volumes:
  stock_control_pg:
  keycloak_pg:
  maven-cache: